---
title: HuMont
timezone: UTC
collections:
  assets:
    title: Assets
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  readings:
    title: Readings
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: Here's a little website in which I log what I learn. It should be useful
  to me, hopefully, it can be useful for you.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
