---
title: HuMont
timezone: UTC
collections:
  assets:
    title: Assets
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  readings:
    title: Readings
    output: true
  uploads:
    title: Uploads
    output: true
  test:
    title: test
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    image: "/assets/no-image.png"
- scope:
    path: ''
    type: readings
  values:
    title: 
    author: 
    rating: 
    start-date: 
    end-date: 
    layout: book
email: 
description: Here's a little website in which I log what I learn. It should be useful
  to me, hopefully, it can be useful for you.
baseurl: 
url: 
github_username: humont
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
